---
apiVersion: v1
kind: List
items:
 - apiVersion: autoscaling/v2beta2
   kind: HorizontalPodAutoscaler
   metadata:
      name: redis-deployment
   spec:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: redis
      minReplicas: 1
      maxReplicas: 3
      metrics:
      - type: Resource
        resource:
          name: cpu
          targetAverageUtilization: 60
      - type: Resource
        resource:
          name: memory
          targetAverageUtilization: 80


 - apiVersion: autoscaling/v2beta2
   kind: HorizontalPodAutoscaler
   metadata:
      name: web-app-hpa
   spec:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name:  web-app
      minReplicas: 1
      maxReplicas: 3
      metrics:
      - type: Resource
        resource:
          name: cpu
          targetAverageUtilization: 60
      - type: Resource
        resource:
          name: memory
          targetAverageUtilization: 80