---
apiVersion: v1
kind: List
items:
 - apiVersion: autoscaling/v2
   kind: HorizontalPodAutoscaler
   metadata:
      name: redis-deployment-hpa
   spec:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: redis-deployment-pod
      minReplicas: 1
      maxReplicas: 3
      metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 60
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 80


 - apiVersion: autoscaling/v2
   kind: HorizontalPodAutoscaler
   metadata:
      name: web-app-hpa
   spec:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name:  web-app
      minReplicas: 1
      maxReplicas: 3
      metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 60
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 80