apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: postgres-deployment
    app: web-app
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
       name: postgres-deployment
       app: web-app
  template:
    metadata:
      labels:
         name: postgres-deployment
         app: web-app
    spec:
      containers:
      - image: postgres:latest
        name: postgres
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to POSTGRES_DB
              name: postgres-config
              # Specify the key associated with the value
              key: POSTGRES_DB   
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        persistentVolumeClaim:
            claimName: postgres-data-pvc        
