apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-app-service
  name: web-app-service
spec:
  type: LoadBalancer #NodePort
  ports:
  - name: "web-port-service"
    port: 443
    targetPort: 80
    #nodePort: 31000
  selector:
    app: web-app