---
apiVersion: v1
kind: List
items:
 - apiVersion: autoscaling/v2
   kind: HorizontalPodAutoscaler
   metadata:
      name: redis-deployment-hpa-{{ .Release.version }}
   spec:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: redis-deployment-pod-{{ .Release.version }}
      minReplicas: {{ .Values.autoscaling.redis.minReplicas }}
      maxReplicas: {{ .Values.autoscaling.redis.maxReplicas }}
      metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: {{ .Values.autoscaling.redis.targetCPUUtilizationPercentage }}
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: {{ .Values.autoscaling.redis.targetMemoryUtilizationPercentage }}


 - apiVersion: autoscaling/v2
   kind: HorizontalPodAutoscaler
   metadata:
      name: web-app-hpa-{{ .Release.version }}
   spec:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name:  web-app-{{ .Release.version }}
      minReplicas: {{ .Values.autoscaling.webServer.minReplicas }}
      maxReplicas: {{ .Values.autoscaling.webServer.maxReplicas }}
      metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: {{ .Values.autoscaling.webServer.targetCPUUtilizationPercentage }}
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: {{ .Values.autoscaling.webServer.targetMemoryUtilizationPercentage }}