apiVersion: v1
kind: Service
metadata:
  name: postgres-service-{{ .Release.version }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
         name: {{ .Values.postgresql.podLabels.name }}
         app: {{ .Values.webServer.podLabels.app }}
     