apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-db-data-pv-{{ .Release.Name }}
  labels:
    type: local
spec:
  storageClassName: {{ .Values.postgresql.persistence.storageClass}}
  capacity:
    storage: {{ .Values.postgresql.persistence.size }}
  accessModes:
    - {{ .Values.postgresql.persistence.accessModes }}
  hostPath:
    path: {{ .Values.postgresql.persistence.hostPath.path }}
