apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
spec:
  storageClassName: manual
  volumeName: postgres-db-data-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
