apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-{{ .Release.version }}
type: Opaque
data:
  postgres-user: {{ .Values.postgresql.postgresqlUsername }}
  postgres-password: {{ .Values.postgresql.postgresqlPassword }}
