apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-{{ .Release.Name }}
type: Opaque
data:
  postgres-user: {{ .Values.postgresql.postgresqlUsername | b64enc  }}
  postgres-password: {{ .Values.postgresql.postgresqlPassword | b64enc  }}
